# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- project:
    check:
      jobs:
        - noop
    gate:
      jobs:
        - noop
    post:
      jobs:
        - governance-upload-git-mirror

- job:
    name: governance-upload-git-mirror
    parent: upload-git-mirror
    description: Mirrors airship/governance to airshipit/governance
    vars:
      git_mirror_repository: airshipit/governance
    secrets:
      - name: git_mirror_credentials
        secret: governance-airshipit-github-secret
        pass-to-parent: true

- secret:
    name: governance-airshipit-github-secret
    data:
      user: git
      host: github.com
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
      ssh_key: !encrypted/pkcs1-oaep
        - Zut3RUXKeJBtz7mgJw/RiPGs6fu+8gDhuIknuGFEjrmJro+CGOzKFcV+r1s462NBcroKc
          QydNh7kgNs1EzaiYbKU4tq49bvSErmOUX52mxJJwC4zQB1eWZUpAZ72EWW2uPl+ymCrhk
          vFKgnrDSSlBDprn6+h06Hh07wgu8zqEx0b+fGDTppVqysVIVtJfl5njgENP56Kr1o3VdL
          yRBp+oTgXj5DgjYhX6+wzlymtY2eoeirETDybkvWxhSLOD/muLNI5ByRSC/BvnRqLdYCp
          6veP5GAfgQTrV0g8CaeC9oAJ3dBlUXMXsNZlIKNaGQm1ZpFTUYxV3HZ1lx7mbwZDAjdyx
          p2U9NYMsVW6d8yQhxNpqdF8o/gtTx4lAGnVc95C+g+aDTI5HJ9y2MN/02Y4JfdlTf3cki
          WVFZsje7VnnDG2pbJgGr1rny+RTPFl3FNF/ETuvVB1XDfI3ZdvbO21rpQVKykAKCIHPvP
          pK4HfY/3itGig3bgIPo/hoSBmOG1EUqBCLrLBQtg3KnPfaU13TfTKA0xmmrvu2vhG0eiK
          kj2EBSGdKusIeQtfgHxjFOvtFGXRgKi2bfuQ+y/n+zmn4ucwKttrHvH77RHlYvbvZBIx/
          z6U6qKXOPzZJcUo1QjlHs+HKtoyFdprFHoI0NsMoxZ//ynylGa5ZIY3WWThd2s=
        - QzNvxqlw34M+gV+aZpN95xP7PPplJm+FgOKdnT1g024kJFtvIxAE3zVU+pAWOHNcf9Csi
          GyCwXSKSxzl7kBdo9mGUW6RE+mbnMtMOpVS4BK3DFp514bgarM/M5Ncgpr9iYckPTy6+I
          BHmzduUhKG0oCNuG/lHUTgsFZ7hf0E4xgy2xr8QBVE1osQKX3Wabn5yOaNwqIQjbsNxxx
          UKEwsIL5IvvGZEnjjBJuBWO99mLauN+utVnF1gesV7RhlOQ5hjEl8dXa5NmFOYA6fQnOi
          W1bBKHMXvXRoDL5OgfsDt0xzlfJiAzTXPRHUpFXOAhkZ2IeEJqqbN+349nZ5A0E0SeGbc
          QS4WY4t/VMW17D8Kxn/lXeNQXuWavjBxBZ9SM30gB0u8u4WFpk7umlRCjCCDeL8H1Z5lr
          RPeX9MmbtsQmniuYCfZJsgavt6s0G2MKNGXVudf9fPLMaWORwGRxd3BLBnFCRUiFn2WmB
          0eERFJMNQ6cr4aQDRGT54cg6FZ87dVz68tlO1MYwfH2hxE8u1hmRvVvK0gn81ioz4kQXR
          qKHkz9XmKYPVb5WJFYnxRw3inQtJp4cmUs6b6eUMDs6m656dsxK0YgKv4KnoS1WLYT67i
          VyiDLo3GDkKPaxBVlHv5lufVsWhoSuRDxgs7JLLPMZ76crCggAZWMU0Gld3HBI=
        - JEPU3lquBQDwTQJTrwepJwns50siGkWePsnf0oCoC9VvcOHpEo2WcnsNALHiOa+2/wznd
          5CVotw+nmnnuye8Ef8VCQmTC0w6ohCZ4c3UnClkxDa5JnXghK5bqMpOAQcM7oRWBib86x
          MFmIYESE4zF99/iCpwDGXGOqDxDA4vsbzNJEpoKp2fFDp0mbD74JSn+79gzQOKkL7uKM+
          ncHF/dfY6FKXjLnR/SLCCbXYU7jMWRACkJRIdV6xym/XpkpYpQLrhjxjkgoPYCpzQP9b2
          fm1WYTXYNqsDOBzgij+1ZOMAh6/A3c2wrrTtgL7iDRMt5YcmdAX7fY4WnQoGZLcOaKOAj
          p3rMCEfRFFoutYAjp75l23xIhCwlUe4B7dTXzc9gX2gf4ks7nh4wyB586vstf5Se3xESF
          9tT6+10U/yM+NPH5VxA7ypLgwQBXIl5bkpSloD0m2LrQS9HSTJ9mzqg5r2bumsG6sAk4B
          ohLp7ZvhgUNrPtTYpMgAGyQMI2ikevt6PcBvK7I7F6JaYgRSVT3SU7IscBXaUIyvvsHk8
          Sfel5MGDZ1HRS5BaTvNd8LQtEHZQBuhzjFm+uVoJND69DdwZjR43ZigFx36pnnMqkSHEa
          EdKZb6L4U+bryVE2OACzLdWzdsS/W+2jb2RCPCEGrfi9gbW9pgJ/CV3B86PIf4=
        - d4WLbMp727eRW8Sq/7DUfyyQVn9wY0VQULHXt9vge5ib0Qqpdwn5JADdEGINunlsHlEBl
          W8XAYNrSsGb/5uwNvZna/hyN/O46PhFGyToK7Lg9mUBM8ywDKrvrlByDGco1zEYLm3y2f
          eyGNp2C1PgjFMD757qsbCOVsPaUaIpcujMbTX6fxexNZ2dqdsvN+OwEK+NIJTLxbuUxOt
          ubbmd1WtIGP8wNfVXFWyC6FLH/9+kX/O0qd+dPBHgDh8sxEgE7Tmd/9mVYoOSKeBaXp58
          /plHzb4DFz+0hNzcBiYuo4FI2UWSmgdoNqEro0FyJ7enx2TB7bTrYqssxwloRtwcPmP9D
          bBmbPc4Y+KIYjNWCr7HsDkqce1Mf11EQCd11UCMH8hWOW5bC892jvqn4Fw9Xe30Vqu1Uy
          4yG9IniylgP73WNq5eUS0GIs3eOLS67WIuEnwoZ/AMUO4txvNhoAWMBMwTTtJ8lrOpleX
          9fI5HEZ6pfw7cADYdyU9ww7BniyZz/C/CZQgVVzfXc+meA9qXAm5FlMLBhj//57hyFCmK
          m1/mFQU/LNWFWMPxHHXpQbGFUM1jicMVqH1avIacdfDPShg9MSPm7jU/Tqbr+gdB8tFG6
          JlQVIbn3DEZ5gsxufHv61mGolT1R3e8eCWctnR531OJq28qXTBfL77BNZCkAyw=
